imports_layout = "HorizontalVertical"
empty_item_single_line = false
use_small_heuristics = false
imports_indent = "Block"
reorder_imports = false
fn_single_line = false
comment_width = 100
max_width = 120
tab_spaces = 2